/* Generated By:JavaCC: Do not edit this line. SimpleSchemeParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleSchemeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int String = 13;
  /** RegularExpression Id. */
  int EXPONENT = 14;
  /** RegularExpression Id. */
  int Constant = 15;
  /** RegularExpression Id. */
  int Identifier = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"(\"",
    "\"define\"",
    "\")\"",
    "\"load\"",
    "\"if\"",
    "\"lambda\"",
    "\".\"",
    "<String>",
    "<EXPONENT>",
    "<Constant>",
    "<Identifier>",
  };

}
